### ISSUE TITLE
https://krnl.rocks/api/getkey

### ISSUE THREAD

**Issue by Uranite** [Sainan/Universal-Bypass#1235]
https://krnl.rocks/api/getkey
yes pls

**Comment by firecoder1** [comment]
For some reason, it also detects even if it is uninstalled or disabled, maybe not an issue with UB [(probably because there aren't actually any tasks on the Linkvertise page) ](https://gyazo.com/f4264049fd5a49c5519295c271966fcf) 

![image](https://user-images.githubusercontent.com/55807755/82145017-b8434780-983f-11ea-9d4d-c398ef708b76.png)

**Comment by Uranite** [comment]
i just checked and its 85 seconds, i tried 80 seconds and it got detected

**Comment by Roux2023** [comment]
Now they detect it i tried it just today and now it detects it even with the timer.

**Comment by Uranite** [comment]
try changing it to 100 seconds or something if it doesn't work try adding 10 or 5 or 20 or whatever u want and if it works try removing 5 seconds or 10 and see it if works

**Comment by gooduser21** [comment]
Ok so i found out that u cant bypass linkverties but if u keep trying it will soon work :)

**Comment by Uranite** [comment]
it seems to work with 85 seconds timer

**Comment by Uranite** [comment]
@Sainan Can you please add krnl bypass to injection_script.js?

**Comment by Sainan** [comment]
You can open a PR. I'm not touching Linkvertise until the lawsuit is resolved.

**Comment by Uranite** [comment]
okay

**Comment by TheDeathDoIIi** [comment]
как получить ключ для скрипта
