### ISSUE TITLE
No longer bypassing on Firefox Android

### ISSUE THREAD

**Issue by supernoodled** [Sainan/Universal-Bypass#1407]
It was working about a month ago, but now it doesn't bypass known working (already crowd bypassed before) links, and if the link hasn't been crowd bypassed before it will not prompt to say that it's not.

Using Firefox Android 68.11.0 and Universal Bypass 13.12.4

**Comment by FireMasterK** [comment]
Provide logs using Firefox's remote/usb debugging if you belive this is an issue caused by Universal Bypass.

**Comment by kevin01523** [comment]
#1405

**Comment by Sainan** [comment]
Some people in that other thread were saying it worked in the previous version but [comparing them](https://github.com/Sainan/Universal-Bypass/compare/a10d4d612a682654f4d0ae3bd9791decfafdb46e...331b121f995c298a3247cc55e25d2606942dcd4a) doesn't show anything interesting, and AnyLint is also not complaining.

Now, in trying to debug this I was forced to install Firefox Nightly instead of the normal Firefox for Android but this is apparently now so new and fresh that they have to cherry-pick supported extensions. Once again a -20 IQ move by Mozilla. Seriously fuck that company.

**Comment by supernoodled** [comment]
It seems it's not fully broken, as in after doing the captcha and clicking get link on a site, I can see the extension appearing and bypassing trackers.

**Comment by kevin01523** [comment]
You can install the latest and closer firefox version to the release before the fenix firefox aka 79.0 from fdroid its called firefox fennec or you can install the apk from qoo app or apkhere or something as long at its version  68.11.0
