### ISSUE TITLE
[REQ] Can you add this web to bypass ?

### ISSUE THREAD

**Issue by valdev-fs** [Sainan/Universal-Bypass#1505]
https://ad4msan.com/?3bc63b4a9e=Umgvc3BURmZxYkVLYmlTYzMvazlxZldKclRzZ29ZN2gzOVlOL1VxTUljc0tOM1YwZHkzY0J3bXZDNm03ZG9mTm1GOW9Kd0RBTVJzWnJGVnNkTlBBc2wxbWtpT0YrbXJ0S2pGVjUvSG5TY2s9

Thank You

**Comment by Lya-chan** [comment]
The site is suck, the waiting time 50s

-

**Comment by Cyberavater** [comment]
Destination; http://bukadrive.com/file/3431777339

UB says it's currently under CB, which is wrong cuz I've waited myself and still the destination is not saved.

BTW, the link *seems* locally decryptable, it should be under default bypass if anybody can figure out the decryption method.

**Comment by Cyberavater** [comment]
@Sainan Can you confirm if my theory is right or wrong?

**Comment by Sainan** [comment]
it is crowd-bypassed, but I assume it's the kind of site where the link always changes so a bypass clipboard would need to be assigned from wherever they get the link from.

**Comment by Cyberavater** [comment]
@Sainan If you think this link is locally decryptable, I'll ask for help from the Reddit decryption group.

**Comment by Sainan** [comment]
That's not at all what I said, but from what I know about that template is that every instance has its own encryption key.

**Comment by Cyberavater** [comment]
Okay, then I'll NOT ask them for help, since it's not locally decryptable.

**Comment by Sainan** [comment]
I mean, it might be nice to know the algorithm and maybe some way to crack the password, but this is a template used on many sites, so the password cracking must be feasable to execute for hundreds of different targets. And if any modern encryption was chosen, that simply won't happen.

In any case, unless OP decides to respond with the source of the example link, this issue is going nowhere.
