### ISSUE TITLE
Can't land on the destination page

### ISSUE THREAD

**Issue by a092devs** [Sainan/Universal-Bypass#1545]
Enabled universal bypass on firefox nightly using this [guide](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/)
Not able to land on destination page. It shows whote page only.
Stuck in this URL: [here](https://universal-bypass.org/bypassed?target=https%3A%2F%2Fget-to.link%2Fthe-glorias-2020-720p-webrip-2ch-x265-hevc-psa75462%2F&referer=https%3A%2F%2Fexpertvn.com%2Fphan-loai-tan-nhiet-nuoc.html%3F%23W4fe)

**Comment by Sainan** [comment]
The extension properly registers a handler for `https://universal-bypass.org/bypassed` because it is technically not a real URL and only serves the purpose of safely bringing you to the target with the proper context so the destination won't break or know you're using Universal Bypass.

Mozilla, however, as a company never does anything right. You could _try_ complaining to them... maybe they'll care about you?

**Comment by teohhanhui** [comment]
@Sainan wouldn't it be more helpful to open an issue on fenix repo? 🙇

**Comment by FireMasterK** [comment]
You're free to open an issue there as this is not a Universal-Bypass issue.
