### ISSUE TITLE
t.co > ow.ly

### ISSUE THREAD

**Issue by unbeatable-101** [Sainan/Universal-Bypass#1570]
https://t.co/0GMVNE4jWn

This link will not work.

**Comment by Sainan** [comment]
If they wanna track you so badly that they'll gladly break their own links, I can't really do anything about it, but you're free to disable the tracker bypass.

**Comment by FireMasterK** [comment]
It looks like that website is HTTP only, seems to refuse my connection altogether when connecting to port 443. So, it's a broken website for sure.

**Comment by Sainan** [comment]
If that's the case, "HTTPS Everywhere" would break them as well, right? Maybe they think that a user who has pro-privacy extensions is not a user they want to bother with. Well, the world is inhabited by greedy humans; what else is new? Anyway, for the sake of Universal Bypass not breaking this one shitty company's linkshitter, this issue can be fixed. Thanks for figuring out what the issue was, because I was only looking at headers, not even considering that anyone in 2020 would reject HTTPS.
