### ISSUE TITLE
Suggestion/Request

### ISSUE THREAD

**Issue by obeho** [Sainan/Universal-Bypass#1577]
I use Firefox on pc with several extensions like uBo, uMatrix, HTTPS everywhere, etc. Most times on sites, I have to go through all the captcha checking and waiting for the timer, then, at the end the extension detects it and redirects to the destination site.

I have seen some open [issues](https://github.com/Sainan/Universal-Bypass/issues/1197) mentioning something called CSP, and overlapping of extensions, bugzilla, etc. I understand there's some friction there. I dont know whether the issue on my pc is because of this issue or not. But I assume so, because when I open the same link in incognito mode, where those extensions are not there, I get redirected fine.

I hope you see that non tech-savvy people also use this extension. So, would like to propose a different way of bypassing.

I have some link like https://iir.ai/KKB9. I paste this link in a search bar that gets displayed, when I click on the extension. (see below pic for reference)

`There's some problem with image uploading, please open this [link](https://i1.wp.com/beebom.com/wp-content/uploads/2016/05/DuckDuckGo-Extension.jpg?resize=640%2C400) instead`

Click enter, loading....... and boom, destination site gets displayed. (The output can either be as simple as a url display below the search bar, or getting redirected automatically to the destination)

**Comment by Sainan** [comment]
I don't mean to exclude non-tech-savvy people, but the issue is in the way that Firefox handles a very specific case in a way that results in overblocking (and they knew that when they made it that way), so I can only say that Mozilla made a mistake, give them the bug report to upvote and follow, and that's about it.

As for your actual suggestion/request, it is something that I know a few users would like, but Universal Bypass isn't a service; it's an ad-blocker, in the sense that it applies certain rules to certain sites. The most obvious/common case is that you encounter a link shortener that makes you wait, Universal Bypass finds the destination, and puts you on your way, but that's not all cases, and extracting all of those cases would be needlessly tedious, and I think that wouldn't even solve the CSP issue with Firefox.
