### ISSUE TITLE
Remove "before-navigate.html"

### ISSUE THREAD

**Issue by privacyguy123** [Sainan/Universal-Bypass#1681]
Useless and unncessary IMO - I can remove it myself but then the addon won't sideload into FireFox because they have removed the ability to do this.

Unless anybody can talk me through how to load my own edited version?

**Comment by Sainan** [comment]
> Useless and unncessary IMO

Okay, but is your opinion based on having written this extension and having faced all the issues? No.

**Comment by privacyguy123** [comment]
Are you saying you can't code in an option to remove this splash page? I'm finding everything working just fine without it.

**Comment by Sainan** [comment]
I'm saying it fulfils a purpose. Namely, providing a proper referer header after a redirect. It's also not a splash page, and it has no impact on the actual speed of the redirect, as that is still mostly down to networking. You just notice the before-navigate page because the internet tends to be a bit slower than your average human reaction time.

**Comment by privacyguy123** [comment]
And I'm saying bypasses work fine with the page removed from the code ...

**Comment by Sainan** [comment]
It might be the vast majority of them, but no one likes edge cases.
